# Generated by Django 6.0.3 on 2026-04-01 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_guild_id', models.BigIntegerField(db_index=True)),
                ('channel_id', models.BigIntegerField()),
                ('message_id', models.BigIntegerField(default=0)),
                ('team_home', models.CharField(max_length=255)),
                ('team_away', models.CharField(max_length=255)),
                ('match_at_display', models.CharField(max_length=512)),
                ('prize', models.TextField(blank=True, null=True)),
                ('closed', models.BooleanField(db_index=True, default=False)),
                ('gols_casa_final', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gols_visitante_final', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BolaoBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_user_id', models.BigIntegerField()),
                ('username', models.CharField(max_length=80)),
                ('prediction', models.CharField(max_length=32)),
                ('team_pick', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bolao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='bolao.bolao')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
